-- PRIMERO PONEMOS LA CIUDAD Y EL TAMANIO
SELECT CITY, LENGTH(CITY)
-- DE LA TABLA
FROM STATION
-- ODRDENA POR NUM DE CARACTERES ASCENDENTE LA CIUDAD
ORDER BY LENGTH(CITY) ASC, 
-- SI 2 CIUDADES TIENE 3 CARACTERES ORDENA ALFABETICAMENTE
CITY ASC
-- LIMITA A QUE SOLO SALGA UNO
LIMIT 1;

-- TODA ESTA HACE LO MISMO 
SELECT CITY, LENGTH(CITY) 
FROM STATION
-- UNICO CAMBIO ORDENA DESCENDENTE
ORDER BY LENGTH(CITY) DESC, CITY ASC
LIMIT 1;
