-- PEDIMOS EL NOMBRE DE LOS CONTINENTES
SELECT COUNTRY.CONTINENT, 
-- AVG DA EL VALOR PROMEDIO DE TODA UNA COL
-- FLOOR LO DEDONDEA PARA ABAJO 
FLOOR(AVG(CITY.Population))
-- PEDIMOS LA INFO DE LA TABLA CITY
FROM CITY
-- INCLUIMOS COUNTRY 
-- NADA MAS DE PIDE INFO DE AMBAS TABLAS 
-- DA IGUAL EL ORDEN SI FROM COUNTRY JOIN CITY O COMO ESTA AHORA
JOIN COUNTRY
-- SOLO VAMOS A IGUAL AMBOS CODES
ON CITY.CountryCode = COUNTRY.Code
-- AGRUPAR POR CONTIENENTE
GROUP BY COUNTRY.Continent;
